[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rodio = "0.16.0"
hound = "3.5.0"
portaudio = "0.7.0"
diesel = { version = "2.0.0", features = ["sqlite", "chrono"] }
dotenvy = "0.15"
chrono = "0.4"